### ISSUE TITLE
Import project but script error“CS0246: The type or namespace name 'Stalo' could not be found”

### ISSUE THREAD

**Issue by Gaolingx** [stalomeow/StarRailNPRShader#2]
Thanks for your sharing. When I tried import your project but the editor has a error that "Assets\ResModules\Shaders\StarRailNPRShader-main\Scripts\Editor\MaterialDrawers\HSRMaterialIDFoldoutDrawer.cs(4,7): error CS0246: The type or namespace name 'Stalo' could not be found (are you missing a using directive or an assembly reference?)" It seemed that some references or scripts has been missed. :(

**Comment by stalomeow** [comment]
You **must** import package [ShaderUtilsForSRP](https://github.com/stalomeow/ShaderUtilsForSRP) as well. I have mentioned it in [Requirements](https://github.com/stalomeow/StarRailNPRShader#requirements).

**Comment by stalomeow** [comment]
If you have solved the problem, please close this issue.
