### ISSUE TITLE
我创造了个材质并贴了贴图，为啥整个都是透明的

### ISSUE THREAD

**Issue by Spphire** [stalomeow/StarRailNPRShader#4]

**Comment by Spphire** [comment]
新建默认材质球本身就是不可见的
![image](https://github.com/stalomeow/StarRailNPRShader/assets/56157591/4e9bfca7-8306-45c8-83b1-5b9c6cf0cb9a)

**Comment by stalomeow** [comment]
> 新建默认材质球本身就是不可见的 ![image](https://user-images.githubusercontent.com/56157591/275224672-4e9bfca7-8306-45c8-83b1-5b9c6cf0cb9a.png)

加RendererFeature了吗

**Comment by Spphire** [comment]
原来如此 tql

**Comment by stalomeow** [comment]
不管什么项目，用之前先看 README。
