### ISSUE TITLE
关于描边的一些建议

### ISSUE THREAD

**Issue by Spphire** [stalomeow/StarRailNPRShader#5]
在薄模型的地方比如裙摆，描边会在模型背面产生大色块：
![image](https://github.com/stalomeow/StarRailNPRShader/assets/56157591/1bfacbbb-75c8-46f8-83d1-db61b64166b3)
可以在outline pass后面再渲染一层背面
![image](https://github.com/stalomeow/StarRailNPRShader/assets/56157591/6e2b9feb-ea02-4355-bbc4-cec066dc9e76)
![image](https://github.com/stalomeow/StarRailNPRShader/assets/56157591/12dfc25b-bfd4-4a08-87d7-48e8709877e9)

**Comment by stalomeow** [comment]
其实有个描边参数里有个ZOffset。微调这个也行。一定要微调，数值一般是-1e6~-1e4这样
