### ISSUE TITLE
Question on how to set up a material

### ISSUE THREAD

**Issue by RedCorpDE** [stalomeow/StarRailNPRShader#6]
Is there the possibility for you to upload the materials, that you used for your renderings?
I'm having a hard time achieving something similar, mainly with the Face-Shader.
I really appreciate any help you can provide.

**Comment by stalomeow** [comment]
MMD model? Did u add SyncMMDHeadBone component?

**Comment by RedCorpDE** [comment]
Both, faces are super blown out, is there a way for you to upload your examples?

**Comment by stalomeow** [comment]
No... I won't upload them. Textures and models are owned by miHoYo. I can not distribute them without the permission of miHoYo.

**Comment by stalomeow** [comment]
You can upload some pictures and show me some detailed information.
