### ISSUE TITLE
材质丢失

### ISSUE THREAD

**Issue by kkze** [stalomeow/StarRailNPRShader#7]
![sp20240304_025121_066](https://github.com/stalomeow/StarRailNPRShader/assets/65899966/da5c2f3d-6c0a-4a27-a5b0-5959cba1eec5)
我添加RendererFeature 后材质好像加载不出来
![Snipaste_2024-03-04_02-54-45](https://github.com/stalomeow/StarRailNPRShader/assets/65899966/6147c8ba-72d5-4445-810e-9bb78a2d54f0)
![image](https://github.com/stalomeow/StarRailNPRShader/assets/65899966/008ae844-e053-4dd6-b1b0-03119773e438)

我是新手，研究了半天没找到问题，如果是常识上的配置出错还请海涵❤️

**Comment by stalomeow** [comment]
unity版本是什么，还有urp的版本

**Comment by stalomeow** [comment]
shader有报错吗

**Comment by kkze** [comment]
> shader有报错吗

Shader error in 'Honkai Star Rail/Character/Hair': Couldn't open include file 'Packages/com.unity.render-pipelines.core/ShaderLibrary/FoveatedRenderingKeywords.hlsl'. at /Users/alyssa/StarRail/Library/PackageCache/com.stalomeow.star-rail-npr-shader@e9a6e51cec/Shaders/Character/Shared/CharMotionVectors.hlsl(26)

Compiling Subshader: 0, Pass: HairFakeTransparent, Vertex program with _ADDITIONAL_LIGHTS _MAIN_LIGHT_SHADOWS_CASCADE _MODEL_MMD
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: FOG_EXP FOG_EXP2 FOG_LINEAR SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING _MAIN_LIGHT_SHADOWS _MODEL_GAME

**Comment by kkze** [comment]
这是我的包管理器，是缺少依赖嘛..
![Snipaste_2024-03-04_08-52-33](https://github.com/stalomeow/StarRailNPRShader/assets/65899966/f74aa289-1de6-465b-8da0-da48ede551a8)

**Comment by stalomeow** [comment]
把urp升到14.0.10吧

**Comment by stalomeow** [comment]
把core rp library 升级一下

**Comment by kkze** [comment]
我将unity版本升级为2023.2.11f1c1解决了问题，core rp library 为16.0.5，不过又出现了新的报错，具体影响我还没发现，不过当前issues的问题应该算是解决了。
`Library\PackageCache\com.stalomeow.star-rail-npr-shader@e9a6e51cec\Editor\Build\ShaderStripper.cs(30,61): error CS0012: The type 'IStripper' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.RenderPipelines.Core.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
`
